In [ ]:
%pip install SimpleITK==2.4.0
%pip install numpy==1.26.4
%pip install pyradiomics==3.1.0

In [1]:
import radiomics
import numpy as np
import SimpleITK as sitk

In [2]:
imageSize = (3, 3, 3)

mask_data = np.ones(imageSize, dtype=int)
# mask_data = np.zeros(imageSize, dtype=int)
# mask_data[0,0,0] = 1
# mask_data[2,2,2] = 1
mask = sitk.GetImageFromArray(mask_data)
# image = sitk.GetImageFromArray(np.random.randint(0, 100, size=imageSize))
image_data = [[[81, 98,  1],
  [22, 74, 98],
  [78, 32, 60]],

 [[59,  8, 38],
  [ 4, 82, 67],
  [70, 94, 98]],

 [[38, 27, 89],
  [59,  0, 93],
  [70, 60, 10]]]

image = sitk.GetImageFromArray(image_data)

In [3]:
print(sitk.GetArrayFromImage(image))
print(sitk.GetArrayFromImage(mask))

[[[81 98  1]
  [22 74 98]
  [78 32 60]]

 [[59  8 38]
  [ 4 82 67]
  [70 94 98]]

 [[38 27 89]
  [59  0 93]
  [70 60 10]]]
[[[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]]


In [4]:
import radiomics.featureextractor
import os

paramsFile = os.path.abspath(r'params.yaml')
extractor = radiomics.featureextractor.RadiomicsFeatureExtractor(paramsFile)
featureMap = extractor.execute(image, mask, voxelBased=True)

d:\Desktop\workspace\todo\.venv\lib\site-packages\radiomics\glcm.py:258: RuntimeWarning: Mean of empty slice
  return numpy.nanmean(ac, 1)
d:\Desktop\workspace\todo\.venv\lib\site-packages\radiomics\glcm.py:294: RuntimeWarning: Mean of empty slice
  return numpy.nanmean(cp, 1)
d:\Desktop\workspace\todo\.venv\lib\site-packages\radiomics\glcm.py:312: RuntimeWarning: Mean of empty slice
  return numpy.nanmean(cs, 1)
d:\Desktop\workspace\todo\.venv\lib\site-packages\radiomics\glcm.py:329: RuntimeWarning: Mean of empty slice
  return numpy.nanmean(ct, 1)
d:\Desktop\workspace\todo\.venv\lib\site-packages\radiomics\glcm.py:344: RuntimeWarning: Mean of empty slice
  return numpy.nanmean(cont, 1)
d:\Desktop\workspace\todo\.venv\lib\site-packages\radiomics\glcm.py:374: RuntimeWarning: Mean of empty slice
  return numpy.nanmean(corr, (1, 2, 3))
d:\Desktop\workspace\todo\.venv\lib\site-packages\radiomics\glcm.py:390: RuntimeWarning: Mean of empty slice
  return numpy.nanmean(diffavg, 1)
d:\Desktop

In [5]:
features = featureMap['original_firstorder_Energy']
sitk.GetArrayFromImage(features)

array([[[ 32410.,  47948.,  37406.],
        [ 53254.,  81996.,  60470.],
        [ 33544.,  60841.,  49357.]],

       [[ 38064.,  70172.,  54705.],
        [ 67408., 112820.,  81469.],
        [ 45525.,  81571.,  61706.]],

       [[ 15939.,  38442.,  30020.],
        [ 38175.,  70382.,  52160.],
        [ 32457.,  55299.,  42002.]]])

In [6]:
featureMap

OrderedDict([('diagnostics_Versions_PyRadiomics', 'v3.1.0'),
             ('diagnostics_Versions_Numpy', '1.26.4'),
             ('diagnostics_Versions_SimpleITK', '2.4.0'),
             ('diagnostics_Versions_PyWavelet', '1.6.0'),
             ('diagnostics_Versions_Python', '3.9.0'),
             ('diagnostics_Configuration_Settings',
              {'minimumROIDimensions': 2,
               'minimumROISize': None,
               'normalize': False,
               'normalizeScale': 1,
               'removeOutliers': None,
               'resampledPixelSpacing': None,
               'interpolator': 'sitkBSpline',
               'preCrop': False,
               'padDistance': 5,
               'distances': [2],
               'force2D': False,
               'force2Ddimension': 0,
               'resegmentRange': None,
               'label': 1,
               'additionalInfo': True,
               'kernelRadius': 1,
               'voxelBased': True}),
             ('diagnostics_Confi