In [1]:
%pip install SimpleITK==2.4.0
%pip install numpy==1.26.4
%pip install pyradiomics==3.1.0

Defaulting to user installation because normal site-packages is not writeable
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 52.4/52.4 MB 2.8 MB/s eta 0:00:0000:0100:01

[notice] A new release of pip is available: 23.0.1 -> 25.0.1
[notice] To update, run: pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.
Defaulting to user installation because normal site-packages is not writeable
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 18.2/18.2 MB 2.9 MB/s eta 0:00:0000:0100:01

[notice] A new release of pip is available: 23.0.1 -> 25.0.1
[notice] To update, run: pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.
Defaulting to user installation because normal site-packages is not writeable
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 177.9/177.9 kB 902.9 kB/s eta 0:00:0000:0100:01
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.5/4.5 MB 2.9 MB/s eta 0:00:0000:0100:01
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 117.

In [2]:
import radiomics
import numpy as np
import SimpleITK as sitk

In [3]:
imageSize = (3, 3, 3)

mask_data = np.ones(imageSize, dtype=int)
# mask_data = np.zeros(imageSize, dtype=int)
# mask_data[0,0,0] = 1
# mask_data[2,2,2] = 1
mask = sitk.GetImageFromArray(mask_data)
# image = sitk.GetImageFromArray(np.random.randint(0, 100, size=imageSize))
image_data = [[[81, 98,  1],
  [22, 74, 98],
  [78, 32, 60]],

 [[59,  8, 38],
  [ 4, 82, 67],
  [70, 94, 98]],

 [[38, 27, 89],
  [59,  0, 93],
  [70, 60, 10]]]

image = sitk.GetImageFromArray(image_data)

In [4]:
print(sitk.GetArrayFromImage(image))
print(sitk.GetArrayFromImage(mask))

[[[81 98  1]
  [22 74 98]
  [78 32 60]]

 [[59  8 38]
  [ 4 82 67]
  [70 94 98]]

 [[38 27 89]
  [59  0 93]
  [70 60 10]]]
[[[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]]


In [5]:
import radiomics.featureextractor
import os

paramsFile = os.path.abspath(r'params.yaml')
extractor = radiomics.featureextractor.RadiomicsFeatureExtractor(paramsFile)
featureMap = extractor.execute(image, mask, voxelBased=True)

GLCM is symmetrical, therefore Sum Average = 2 * Joint Average, only 1 needs to be calculated


In [6]:
features = featureMap['original_firstorder_Energy']
sitk.GetArrayFromImage(features)

array([[[112820., 112820., 112820.],
        [112820., 112820., 112820.],
        [112820., 112820., 112820.]],

       [[112820., 112820., 112820.],
        [112820., 112820., 112820.],
        [112820., 112820., 112820.]],

       [[112820., 112820., 112820.],
        [112820., 112820., 112820.],
        [112820., 112820., 112820.]]])

In [7]:
featureMap

OrderedDict([('diagnostics_Versions_PyRadiomics', 'v3.1.0'),
             ('diagnostics_Versions_Numpy', '1.26.4'),
             ('diagnostics_Versions_SimpleITK', '2.4.0'),
             ('diagnostics_Versions_PyWavelet', '1.6.0'),
             ('diagnostics_Versions_Python', '3.9.21'),
             ('diagnostics_Configuration_Settings',
              {'minimumROIDimensions': 2,
               'minimumROISize': None,
               'normalize': False,
               'normalizeScale': 1,
               'removeOutliers': None,
               'resampledPixelSpacing': None,
               'interpolator': 'sitkBSpline',
               'preCrop': False,
               'padDistance': 5,
               'distances': [2],
               'force2D': False,
               'force2Ddimension': 0,
               'resegmentRange': None,
               'label': 1,
               'additionalInfo': True,
               'kernelRadius': 2,
               'voxelBased': True}),
             ('diagnostics_Conf