<a href="https://colab.research.google.com/github/ntatfff/todo/blob/202411241258/ColabRadiomicsFeatureExtractor.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Use different version of Python in Google Colab (Python 3.9 or Python 3.10)

In [ ]:
## for python 3.10, run this cell
!wget -O mini.sh https://repo.anaconda.com/miniconda/Miniconda3-py310_22.11.1-1-Linux-x86_64.sh
!chmod +x mini.sh
!bash ./mini.sh -b -f -p /usr/local
!conda install -q -y jupyter
!conda install -q -y google-colab -c conda-forge
!python -m ipykernel install --name "py310" --user

In [1]:
## for python 3.9 run this cell
!wget -O mini.sh https://repo.anaconda.com/miniconda/Miniconda3-py39_4.9.2-Linux-x86_64.sh
!chmod +x mini.sh
!bash ./mini.sh -b -f -p /usr/local
!conda install -q -y jupyter
!conda install -q -y google-colab -c conda-forge
!python -m ipykernel install --name "py39" --user

--2024-12-27 09:16:22--  https://repo.anaconda.com/miniconda/Miniconda3-py39_4.9.2-Linux-x86_64.sh
Resolving repo.anaconda.com (repo.anaconda.com)... 104.16.32.241, 104.16.191.158, 2606:4700::6810:bf9e, ...
Connecting to repo.anaconda.com (repo.anaconda.com)|104.16.32.241|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 61451533 (59M) [application/x-sh]
Saving to: ‘mini.sh’

mini.sh             100%[===================>]  58.60M   101MB/s    in 0.6s    

2024-12-27 09:16:22 (101 MB/s) - ‘mini.sh’ saved [61451533/61451533]

PREFIX=/usr/local
Unpacking payload ...
Solving environment: / - \ done

## Package Plan ##

  environment location: /usr/local

  added / updated specs:
    - _libgcc_mutex==0.1=main
    - brotlipy==0.7.0=py39h27cfd23_1003
    - ca-certificates==2020.12.8=h06a4308_0
    - certifi==2020.12.5=py39h06a4308_0
    - cffi==1.14.4=py39h261ae71_0
    - chardet==3.0.4=py39h06a4308_1003
    - conda-package-handling==1.7.2=py39h27cfd23_1
    - co

In [2]:
! python3 --version

Python 3.9.21


In [8]:
!sudo update-alternatives --install /usr/bin/python3 python3 /usr/local/lib/python3.9 1

update-alternatives: using /usr/local/lib/python3.9 to provide /usr/bin/python3 (python3) in auto mode


In [10]:
%pip install SimpleITK==2.4.0
%pip install numpy==1.26.4
%pip install pyradiomics==3.1.0
%pip install six==1.17.0

In [13]:
%%writefile code.py

import radiomics
import numpy as np
import SimpleITK as sitk
import radiomics.featureextractor
import os

imagePath = 'dataset/BraTS2021_Training_Data/BraTS2021_00000/BraTS2021_00000_flair.nii.gz'
image=sitk.ReadImage(imagePath)
maskPath='dataset/BraTS2021_Training_Data/BraTS2021_00000/BraTS2021_00000_tumor.nii.gz'
mask = sitk.ReadImage(maskPath)

settings = {}
settings['kernelRadius'] = 5
settings['voxelBatch'] = 512
extractor = radiomics.featureextractor.RadiomicsFeatureExtractor(**settings)

featureMap = extractor.execute(image, mask, voxelBased=True)

for featureName, featureValue in six.iteritems(featureMap):
  if isinstance(featureValue, sitk.Image):
    sitk.WriteImage(featureValue, '%s_%s.nrrd' % ('BraTS2021_00000', featureName))
    print('Computed %s, stored as "%s_%s.nrrd"' % (featureName, 'BraTS2021_00000', featureName))
  else:
    print('%s: %s' % (featureName, featureValue))

Overwriting code.py


In [14]:
!python3 code.py

GLCM is symmetrical, therefore Sum Average = 2 * Joint Average, only 1 needs to be calculated
[[[ 32410.  47948.  37406.]
  [ 53254.  81996.  60470.]
  [ 33544.  60841.  49357.]]

 [[ 38064.  70172.  54705.]
  [ 67408. 112820.  81469.]
  [ 45525.  81571.  61706.]]

 [[ 15939.  38442.  30020.]
  [ 38175.  70382.  52160.]
  [ 32457.  55299.  42002.]]]
